// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using world_of_data.Models;

#nullable disable

namespace world_of_data.Migrations
{
    [DbContext(typeof(WoWClassDbContext))]
    [Migration("20230511010417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("world_of_data.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arena2v2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arena3v3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MythicScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WoWClassID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("charName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("iLVL")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterID");

                    b.HasIndex("WoWClassID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("world_of_data.Models.WoWClass", b =>
                {
                    b.Property<int>("WoWClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("classArmor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("className")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("classRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("classSpec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WoWClassID");

                    b.ToTable("WoWClass");
                });

            modelBuilder.Entity("world_of_data.Models.Character", b =>
                {
                    b.HasOne("world_of_data.Models.WoWClass", "WoWClass")
                        .WithMany("Characters")
                        .HasForeignKey("WoWClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WoWClass");
                });

            modelBuilder.Entity("world_of_data.Models.WoWClass", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
